### ISSUE TITLE
Cannot create a DbSet for 'IdentityRole' because this type is not included in the model for the context.

### ISSUE THREAD

**Issue by trebor94** [capesean/openiddict-test#14]
After applying migrations, starting up the server and pressing the "Get Token" button,
the server responds with a HTTP 500. 
According to the logs, instead of using the ApplicationRole the IdentityRole is being used. 

I have not been able to find a solution yet. The full log is as follows:

> System.InvalidOperationException:Cannot create a DbSet for 'IdentityRole' because this type is not included in the model for the context.
>    at Microsoft.EntityFrameworkCore.DbContext.Set[TEntity]()
>    at Microsoft.AspNetCore.Identity.EntityFrameworkCore.UserStore`4.get_Roles()
>    at Microsoft.AspNetCore.Identity.EntityFrameworkCore.UserStore`4.<GetRolesAsync>d__34.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
>    at Microsoft.AspNetCore.Identity.UserManager`1.<GetRolesAsync>d__105.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
>    at OpenIddict.OpenIddictUserManager`1.<CreateIdentityAsync>d__12.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
>    at OpenIddict.Infrastructure.OpenIddictProvider`5.<GrantResourceOwnerCredentials>d__6.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
>    at AspNet.Security.OpenIdConnect.Server.OpenIdConnectServerHandler.<InvokeTokenEndpointAsync>d__17.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
>    at AspNet.Security.OpenIdConnect.Server.OpenIdConnectServerHandler.<HandleRequestAsync>d__5.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
>    at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware`1.<Invoke>d__18.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware`1.<Invoke>d__18.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
>    at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.<Invoke>d__7.MoveNext()

**Comment by trebor94** [comment]
Just after posting I did find the solution. The line 
`services.AddOpenIddict<ApplicationUser, ApplicationDbContext>()` in [Startup.cs](https://github.com/capesean/openiddict-test/blob/master/src/openiddict-test/Startup.cs#L32)
should be changed to
`services.AddOpenIddict<ApplicationUser, ApplicationRole, ApplicationDbContext>()`

**Comment by kyroluskamal** [comment]
You need to add the IdentityRole to the RoleStore
I write the solution for this problem at stackoverflow https://stackoverflow.com/questions/46761397/invalidoperationexception-cannot-create-a-dbset-for-role-because-this-type-is/69230649#69230649
