### ISSUE TITLE
3 errors after building this project

### ISSUE THREAD

**Issue by piotrek-k** [capesean/openiddict-test#4]
![openiddict](https://cloud.githubusercontent.com/assets/5506878/13904916/fee7d4ea-eeb0-11e5-9f4d-f49e11144f81.png)

Something must have changed in dependencies since creating this repo.

**Comment by capesean** [comment]
Yep, there have been a lot of changes to the .NET nightly builds, which aren't in a stable way at the moment, so I'm waiting for them to settle down before updating this repo. I believe this particular issue now requires: `.AddEntityFrameworkCore`.

**Comment by mrmeek** [comment]
When you're targeting the RC2 assemblies on aspnetcidev the current api seems to be like:

`services.AddEntityFrameworkSqlServer()`

I was lucky and stumbled across the name change in some issue on the repo. Please let me know if that works for you.

BTW Sean, I tried to email you via the contact form on your blog and it failed with: 

> Could not deliver message to the following recipient(s):
> 
> Failed Recipient: your-email@gmail.com
> Reason: Remote host said: 550 5.7.1 [BFD] Sender prohibited by SPF

We are on the same path and I think we should share experiences

**Comment by capesean** [comment]
Hi Mike

At the moment, there are lots of issues with the latest builds and with
nuget, so I'm holding off fixing anything until it beds down a bit.

If you'd like to keep up to date with things, I suggest joining one of
these chatrooms:
https://gitter.im/openiddict/openiddict-core
https://jabbr.net/#/rooms/aspnet-contrib

Thanks for the heads-up about the blog.

Regards
Sean

**Comment by kevinchalet** [comment]
FYI, I've finally found a workaround to make both DNX and CLI work and the new OpenIddict packages - that include the latest Identity/EntityFramework changes - are online.

@capesean feel free to ping me if you're having trouble migrating your project :clap:

**Comment by capesean** [comment]
Just updated the repo and this should now build & run fine.
