### ISSUE TITLE
Does not support framework DNX, Version=v4.5.1 for all dependencies?

### ISSUE THREAD

**Issue by shima20** [capesean/openiddict-test#5]
Hi, 

I was wondering if this was still broken?  I was trying restore packages and i get the following....

![image](https://cloud.githubusercontent.com/assets/9735056/13966245/af826b48-f02e-11e5-986d-df113ed9d86a.png)

**Comment by capesean** [comment]
Should work fine, I've just fixed a few minor issues. I've got the 20270 version packages and with `dnvm list` I'm using version 20222 - you got the same?

**Comment by shima20** [comment]
Here is what I have... I'm not exactly sure what I should do.

![image](https://cloud.githubusercontent.com/assets/9735056/13999348/2f83277c-f0f9-11e5-975b-6959eb8a066d.png)

![image](https://cloud.githubusercontent.com/assets/9735056/13999378/549d9c18-f0f9-11e5-9f55-401938f523c1.png)

**Comment by capesean** [comment]
Try this:
1. In your solution folder, i.e. at the folder with global.json in it, you should have the file Nuget.config. It should have contents like this:

```
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <packageSources>
    <add key="AspNetCiDev" value="https://www.myget.org/F/aspnetcidev/api/v3/index.json" />
    <add key="NuGet" value="https://api.nuget.org/v3/index.json" />
    <add key="aspnet-contrib" value="https://www.myget.org/F/aspnet-contrib/api/v3/index.json" />
  </packageSources>
</configuration>
```
1. Open a normal command prompt in your project folder, i.e. at the folder with project.json in it. Type `SET DNX_UNSTABLE_FEED=https://www.myget.org/F/aspnetcidev`. Then type `dnvm upgrade -u`
2. Once you have the latest runtime installed from step 2, in the same command prompt type `dotnet restore`. This step assumes you have the dotnet CLI installed. If not, download and install it from: https://github.com/dotnet/cli

Let me know how that goes?

**Comment by shima20** [comment]
I got to step 2 but when I went to download the installer for windows, it looks like the build is failed?

**Comment by capesean** [comment]
You'll have to ignore that for now - try installing from here: https://get.asp.net/

**Comment by shima20** [comment]
I downloaded the CLI.  I'm getting this...

![image](https://cloud.githubusercontent.com/assets/9735056/14026832/ef73f18e-f1b1-11e5-93e9-726331c71474.png)

**Comment by Icestorm0141** [comment]
@capesean I followed your steps to the letter. Added a Nuget.config file to the solution directory, navigated into the project folder and ran the two commands. They ran, but I got a TON of errors. Any ideas?

[errors.txt](https://github.com/capesean/openiddict-test/files/192264/errors.txt)

**Comment by kevinchalet** [comment]
The compilation issues you're seeing with DNX/VS should be fixed by https://github.com/capesean/openiddict-test/issues/7.

**Comment by shima20** [comment]
I was finally able to compile and the assemblies are fixed!  thank you!
